services:
  # MongoDB Database
  mongodb:
    image: mongo:7-jammy
    container_name: insight360-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-example}
      MONGO_INITDB_DATABASE: insight360
    volumes:
      - mongodb_data:/data/db
    networks:
      - insight360-network
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.runCommand({ping: 1})' | mongosh --quiet || echo 'db.runCommand({ping: 1})' | mongo --quiet"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Backend API
  backend:
    image: ${DOCKER_HUB_USERNAME}/insight360-backend:${IMAGE_TAG:-latest}
    container_name: insight360-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://${MONGO_ROOT_USERNAME:-root}:${MONGO_ROOT_PASSWORD:-example}@mongodb:27017/insight360?authSource=admin
      - JWT_SECRET=${JWT_SECRET:-7f4e0a86bcd844b89a8c62e1c235bc42f0e7e0e279b54688b08f9b2dc85d8ab0}
      - PORT=5000
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - insight360-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Web App
  frontend:
    image: ${DOCKER_HUB_USERNAME}/insight360-frontend:${IMAGE_TAG:-latest}
    container_name: insight360-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - insight360-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongodb_data:
    driver: local

networks:
  insight360-network:
    driver: bridge
